apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-despachos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-despachos
  template:
    metadata:
      labels:
        app: back-despachos
    spec:
      containers:
      - name: back-despachos
        image: 495619789963.dkr.ecr.us-east-1.amazonaws.com/back-despachos_springboot:latest
        ports:
        - containerPort: 8080