apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-despachos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-despachos
  template:
    metadata:
      labels:
        app: back-despachos
    spec:
      containers:
      - name: back-despachos
        image: 495619789963.dkr.ecr.us-east-1.amazonaws.com/back-despachos_springboot:latest
        ports:
        - containerPort: 8080
        env:
        # 1. Forzamos a Tomcat a usar el puerto 8080
        - name: SERVER_PORT
          value: "8080"
        # 2. Las credenciales de BD exactas que funcionaron en ventas
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://innovatech-db.ctfx6aibrdbf.us-east-1.rds.amazonaws.com:3306/innovatech_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Innovatech2026!"
