apiVersion: v1
kind: Service
metadata:
  name: back-despachos-service
spec:
  # Selector debe coincidir con el label de tu deployment back-despachos
  selector:
    app: back-despachos
  ports:
    - protocol: TCP
      port: 8080        # Puerto expuesto por el balanceador
      targetPort: 8080  # Debe coincidir con el containerPort del deployment
  type: LoadBalancer    # Cambiado a LoadBalancer para permitir la conexión externa del frontend
