apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
      - name: back-ventas
        image: 495619789963.dkr.ecr.us-east-1.amazonaws.com/back-ventas_springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SERVER_ADDRESS
          value: "0.0.0.0"
        # URL corregida para apuntar al servicio interno 'mysql-service'
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/innovatech_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
        # Usuario 'root' por defecto para la imagen de MySQL
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Innovatech2026!"
