apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
      - name: back-ventas
        image: 495619789963.dkr.ecr.us-east-1.amazonaws.com/back-ventas_springboot:latest
        ports:
        - containerPort: 8080