apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-ventas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-ventas
  template:
    metadata:
      labels:
        app: back-ventas
    spec:
      containers:
      - name: back-ventas
        image: 495619789963.dkr.ecr.us-east-1.amazonaws.com/back-ventas_springboot:latest
        ports:
        - containerPort: 8080
        env:
        # Usamos variables estándar de Spring Boot para sobrescribir la configuración interna
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://innovatech-db.ctfx6aibrdbf.us-east-1.rds.amazonaws.com:3306/innovatech_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "Innovatech2026!"
