apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho-deployment
  labels:
    app: front-despacho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
      annotations:
        sidecar.opentelemetry.io/inject: "false"
        instrumentation.opentelemetry.io/inject-java: "false"
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        instrumentation.opentelemetry.io/inject-python: "false"
        instrumentation.opentelemetry.io/inject-dotnet: "false"
    spec:
      containers:
      - name: front-despacho
        # URL corregida con tu cuenta real y el nombre exacto del repo
        image: 760666101701.dkr.ecr.us-east-1.amazonaws.com/front-despacho:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
