apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
    spec:
      containers:
      - name: front-despacho
        image: 495619789963.dkr.ecr.us-east-1.amazonaws.com/front_despacho:latest
        imagePullPolicy: Always  # <--- ESTO ES LO QUE TE FALTA. Obliga a bajar la imagen nueva siempre.
        ports:
        - containerPort: 80
